security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        inscrit_en_dur:
            memory:
                users:
                    perenoel: { password: 'travail', roles: ['ROLE_ADMIN'] }
                    gestionnaire: { password: 'gestion', roles: ['ROLE_GESTIONNAIRE'] }
                    secretaire: { password: 'secret', roles: ['ROLE_SECRETAIRE'] }
    role_hierarchy:
        ROLE_ADMIN: ROLE_GESTIONNAIRE
        ROLE_GESTIONNAIRE: ROLE_SECRETAIRE
    encoders:
        Symfony\Component\Security\Core\User\User: 'plaintext'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt))/
            security: false
        gestion:
            pattern: ^/(_(categorie|cadeau|login|logout))/
            anonymous: lazy
            provider: inscrit_en_dur
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: accueil
                # where to redirect after logout
                # target: app_any_route
        secretaire:
            pattern: ^/(_(personne|adresse|login|logout))/
            anonymous: lazy
            provider: inscrit_en_dur
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: accueil
                # where to redirect after logout
                # target: app_any_route
        public:
            pattern: ^/(menu|css|images|js)?
            security: false

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/liste, roles: ROLE_ADMIN }
        - { path: ^/categorie, roles: ROLE_GESTIONNAIRE }
        - { path: ^/personne, roles: ROLE_SECRETAIRE }
