security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    encoders:
        Symfony\Component\Security\Core\User\User: 'plaintext'
        App\Entity\User:
            algorithm: auto
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
        Adresse:
            pattern: ^/(adresse|login|logout)
            anonymous: lazy
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: accueil
        Personne:
            pattern: ^/(personnes|login|logout)
            anonymous: lazy
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: accueil
        Cadeau:
            pattern: ^/(cadeau|login|logout)
            anonymous: lazy
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: accueil

        Categorie:
            pattern: ^/(categorie|login|logout)
            anonymous: lazy
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: accueil
        public:
            pattern: ^/(menu|css|images|js)?$
            security: false
    role_hierarchy:
        ROLE_ADMIN: ROLE_STOCK, ROLE_SECRETAIRE
    access_control:
        - { path: ^/cadeau/$, roles: ROLE_STOCK }
        - { path: ^/categorie/$, roles: ROLE_STOCK }
        - { path: ^/personne/$, roles: ROLE_SECRETAIRE }
        - { path: ^/adresse/$, roles: ROLE_SECRETAIRE }
